# Generated by Django 3.0 on 2020-08-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estate_user', to='estate.Estate', verbose_name='بنگاه'),
        ),
        migrations.AddField(
            model_name='user',
            name='novice',
            field=models.BooleanField(default=True, verbose_name='تازه کار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False, help_text='مدیر یا مدیران بنگاه ', verbose_name='مدیر بنگاه'),
        ),
    ]
