# Generated by Django 3.0 on 2020-08-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200811_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default='09', max_length=12, verbose_name='شماره تلفن'),
        ),
    ]
