# Generated by Django 3.0 on 2020-08-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
