# Generated by Django 3.0 on 2021-02-13 07:58

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='image_default\\default.jpg', upload_to=authentication.models.change_file_name, verbose_name='عکس'),
        ),
    ]
