# Generated by Django 3.0 on 2021-03-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('address', models.CharField(max_length=100, verbose_name='ادرس')),
                ('bio', models.TextField(verbose_name='توضیحات')),
            ],
        ),
    ]
