# Generated by Django 3.0 on 2020-08-11 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='image_default/default.jpg', upload_to='image-advertising/', verbose_name='عکس')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان آگهی')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='لینک')),
                ('description', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[['a', 'فعال'], ['d', 'غیرفعال']], default='d', max_length=1, verbose_name='وضعیت')),
                ('send_in_estate', models.BooleanField(default=False, verbose_name='ارسال در گروه بنگاه')),
                ('send_in_publish', models.BooleanField(default=False, verbose_name='ارسال به صورت عمومی')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, verbose_name='لینک')),
                ('status', models.CharField(choices=[['a', 'فعال'], ['d', 'غیرفعال']], default='d', max_length=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='image_default/default.jpg', null=True, upload_to='images-adv/', verbose_name='عکس')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_images', to='advertising.Advertising', verbose_name='اگهی')),
            ],
        ),
        migrations.AddField(
            model_name='advertising',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_advertising', to='advertising.Category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='advertising',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_advertising', to=settings.AUTH_USER_MODEL, verbose_name='اگهی دهنده'),
        ),
    ]
