# Generated by Django 3.0 on 2020-08-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_advertising_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'ordering': ('date_added',), 'verbose_name': 'اگهی', 'verbose_name_plural': 'اگهی ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
