# Generated by Django 3.0 on 2020-08-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_auto_20200812_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='ادرس'),
        ),
        migrations.AddField(
            model_name='advertising',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت'),
        ),
    ]
