# Generated by Django 3.0 on 2020-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_auto_20200817_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True, verbose_name='لینک'),
        ),
    ]
