# Generated by Django 3.0 on 2020-09-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_estate_address'),
        ('advertising', '0005_auto_20200830_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='estate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_advertising', to='estate.Estate', verbose_name='بنگاه'),
        ),
    ]
