# Generated by Django 3.0 on 2020-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='نام منطقه')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='لینک')),
                ('code', models.IntegerField(verbose_name='کد منطقه')),
                ('status', models.CharField(choices=[['a', 'فعال'], ['d', 'غیرفعال']], default='d', max_length=1, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, unique=True, verbose_name='نام بنگاه')),
                ('code', models.CharField(max_length=25, verbose_name='کد بنگاه')),
                ('status', models.CharField(choices=[['a', 'فعال'], ['d', 'غیرفعال']], default='d', max_length=1, verbose_name='وضعیت')),
                ('area', models.ManyToManyField(related_name='area_estate', to='estate.Area', verbose_name='انتخاب منطقه')),
            ],
        ),
    ]
