# Generated by Django 3.0 on 2020-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='date_make',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان تشکیل'),
        ),
    ]
