# Generated by Django 3.0 on 2020-08-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_estate_date_make'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('code',), 'verbose_name': 'منطقه', 'verbose_name_plural': 'منطقه ها'},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'ordering': ('code', '-date_make'), 'verbose_name': 'بنگاه', 'verbose_name_plural': 'بنگاه ها'},
        ),
    ]
