# Generated by Django 3.0 on 2020-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20200812_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='slug',
            field=models.SlugField(default='', max_length=225, unique=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(default='', max_length=120, unique=True, verbose_name='لینک'),
        ),
    ]
