# Generated by Django 3.0 on 2020-08-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_auto_20200812_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='ادرس'),
        ),
    ]
