# Generated by Django 3.0 on 2021-02-13 07:58

import advert.models
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('poster', models.ImageField(default='image_default\\default.jpg', upload_to=advert.models.change_file_name, verbose_name='پستر')),
                ('detail', models.CharField(max_length=80, verbose_name='جزئیات')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='قیمت')),
                ('area', models.CharField(max_length=150, verbose_name='متراژ')),
                ('stat', models.CharField(max_length=150, verbose_name='منطقه')),
                ('beds', models.IntegerField(verbose_name='اتاق خواب')),
                ('baths', models.IntegerField(verbose_name='حمام')),
                ('wc', models.IntegerField(verbose_name='سرویس بهداشتی')),
                ('garages', models.BooleanField(default=True, verbose_name='پارکینگ')),
                ('house_type', models.CharField(choices=[('V', 'ویلایی'), ('A', 'آپارتمانی'), ('O', 'سایر موارد')], default='O', max_length=1, verbose_name='وضعیت اگهی')),
                ('category', models.CharField(choices=[('B', 'خرید'), ('S', 'فروش'), ('R', 'رهن'), ('A', 'اجاره')], default='S', max_length=1, verbose_name='وضعیت اگهی')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('is_privet', models.BooleanField(default=False, verbose_name='خصوصی')),
                ('year_created', models.IntegerField(verbose_name='سال ساخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان اپدیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('url', models.URLField(blank=True, null=True, verbose_name='ادرس ویدیو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_advert', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image_default\\default.jpg', upload_to=advert.models.change_file_name, verbose_name='عکس')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='advert.Advert')),
            ],
        ),
    ]
