# Generated by Django 3.0 on 2021-03-24 10:26

import advert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20210324_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='statustype',
            field=models.CharField(choices=[('0', 'همه نوع'), ('1', 'ویلایی'), ('2', 'آپارتمانی'), ('3', 'زمین'), ('4', 'سایر موارد')], default='0', max_length=1, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='house_type',
            field=models.CharField(choices=[('0', 'همه نوع'), ('1', 'ویلایی'), ('2', 'آپارتمانی'), ('3', 'زمین'), ('4', 'سایر موارد')], default='0', max_length=1, verbose_name='نوع خانه'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='poster',
            field=models.ImageField(default='image_default\\default.jpg', upload_to=advert.models.change_file_name, verbose_name='پستر'),
        ),
    ]
