# Generated by Django 3.0 on 2021-03-24 10:27

import advert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_auto_20210324_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='poster',
            field=models.ImageField(default='image_default\\default.jpg', upload_to=advert.models.change_file_name, verbose_name='پستر'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='statustype',
            field=models.CharField(choices=[('0', 'همه دسته بندی ها'), ('1', 'تجاری'), ('2', 'مسکونی')], default='0', max_length=1, verbose_name='نوع ملک'),
        ),
    ]
