# Generated by Django 3.0 on 2021-03-24 11:25

import advert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_auto_20210324_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='flooring',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کف پوش'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='poster',
            field=models.ImageField(default='image_default\\default.jpg', upload_to=advert.models.change_file_name, verbose_name='پستر'),
        ),
    ]
