# Generated by Django 3.0 on 2021-03-25 16:15

import advert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0013_auto_20210325_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('1', 'فروش'), ('2', 'رهن'), ('3', 'اجاره')], default='0', max_length=1, verbose_name='وضعیت اگهی'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='poster',
            field=models.ImageField(default='image_default\\default.jpg', upload_to=advert.models.change_file_name, verbose_name='پستر'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
    ]
